controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz

        use_sim_time: true

        position_controller:
            type: position_controllers/JointGroupPositionController

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        velocity_controller:
            type: velocity_controllers/JointGroupVelocityController



position_controller:
    ros__parameters:
        joints:
            - 'Hip_Left_joint' 
            - 'Knee_Left_joint'
            - 'Ankle_Left_joint'
            - 'Wheel_Left_joint'
            - 'Hip_Right_joint'
            - 'Knee_Right_joint' 
            - 'Ankle_Right_joint'
            - 'Wheel_Right_joint'
            - 'Waist_joint' 
            - 'Neck_joint' 
            - 'Arm_Left_joint' 
            - 'Forearm_Left_joint'
            - 'Wrist_Left_joint'
            - 'Arm_Right_joint'
            - 'Forearm_Right_joint' 
            - 'Wrist_Right_joint'
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity